### ISSUE TITLE
Starlette StreamingResponse does not work anymore

### ISSUE THREAD

**Issue by paradoxxxzero** [abersheeran/a2wsgi#58]
It may be related to #45, I can't use starlette `StreamingResponse` with `a2wsgi` since 1.10.1 version. I tracked down to this commit :  https://github.com/abersheeran/a2wsgi/commit/7bc111f916fd700393a633b36a0c740d9a8e4bd1

When using `StreamingResponse`, `ASGIResponder` gets several `receive` messages with `data` as `b''` and content_length as 0 before getting `http.response.start` and `http.response.body` resulting in an empty response.

**Comment by lmignon** [comment]
@abersheeran when using the `StreamResponse` class from starlette, the implementation of the `__call__` method start by a call to `receive()` to check if the connexion to the client is still open https://github.com/encode/starlette/blob/master/starlette/responses.py#L265.  As side effect the  `asgi_receive` method of `ASGIResponder` class will emit a `receive` event https://github.com/abersheeran/a2wsgi/blob/master/a2wsgi/asgi.py#L167 and the processing of this `receive` event into the loop of the event processing in the `__call__` method of the `ASGIResponder` class will emit a `"http.disconnect"`event to the asgi app https://github.com/abersheeran/a2wsgi/blob/master/a2wsgi/asgi.py#L259C51-L259C68. As result, the build of the response into the  `StreamResponse` class will end since it consider the connexion as closed  https://github.com/encode/starlette/blob/master/starlette/responses.py#L237....

What problem are you trying to solve with https://github.com/abersheeran/a2wsgi/commit/7bc111f916fd700393a633b36a0c740d9a8e4bd1?

Why do you need to emit an 'http.disconnect' event when the input stream has been consumed? In an http connections, each request-response cycle is stateless. The connection is closed after the response is sent.

**Comment by abersheeran** [comment]
This seems to be my problem when reading from a TCP stream and reaching EOF, I misunderstood the purpose of disconnect in the ASGI protocol. I will send out a PR soon.

**Comment by lmignon** [comment]
> This seems to be my problem when reading from a TCP stream and reaching EOF, I misunderstood the purpose of disconnect in the ASGI protocol. I will send out a PR soon.

I'm a newbie in this field and it's not so easy to understand how all this code works or should work with regard to the ASGI protocol. Mistakes are human nature. It's only those who come up with solutions who risk making them.
